"""Time-based operation simulation package export for SubCAD.

This module intentionally keeps animated process state separate from the final
CadQuery model.  The STEP/B-Rep chain remains the authoritative finished part;
operation-video keyframes are simulation meshes generated by replaying process
intent from the original stock.
"""

from __future__ import annotations

import json
import math
import time
from pathlib import Path
from typing import Any


SIMULATION_TIMELINE_SCHEMA_VERSION = "subcad.simulation_timeline.v1"

_CUTTING_MOVES = {"feed", "plunge", "arc"}
_NON_CUTTING_MOVES = {"rapid", "retract", "dwell"}

_TOOL_TYPE_MAP = {
    "flat_endmill": "flat_endmill",
    "ball_endmill": "ball_endmill",
    "drill": "drill",
    "chamfer": "chamfer",
    "thread_mill": "thread_mill",
    "dovetail": "dovetail",
    "end_mill": "flat_endmill",
    "face_mill": "flat_endmill",
    "spot_drill": "drill",
}


def build_simulation_timeline(
    stock: Any,
    *,
    output_dir: str | Path | None = None,
    fps: int = 30,
    playback_rate: float = 1.0,
    resolution_mm: float = 0.5,
    keyframe_interval_sec: float = 0.25,
    target: Any = None,
    include_machine: bool = True,
    include_fixtures: bool = True,
    include_process_effects: bool = True,
    max_keyframes: int = 240,
) -> dict:
    """Build a serializable operation-video timeline for *stock*.

    When ``output_dir`` is provided, simulation stock snapshots are exported as
    STL files under ``simulation_states/`` and referenced from the returned
    timeline.  Without an output directory, the same timing/keyframe metadata is
    returned with no mesh paths.
    """

    started = time.perf_counter()
    out = Path(output_dir) if output_dir is not None else None
    states_dir = None
    if out is not None:
        out.mkdir(parents=True, exist_ok=True)
        states_dir = out / "simulation_states"
        states_dir.mkdir(parents=True, exist_ok=True)

    plan = stock.process_plan()
    initial_mesh, initial_source = _initial_stock_mesh(stock)
    if initial_mesh is None:
        return _error_timeline(
            plan,
            error="Cannot create an initial stock mesh for simulation replay.",
            fps=fps,
            playback_rate=playback_rate,
            resolution_mm=resolution_mm,
        )

    mesh_bbox = _mesh_bbox(initial_mesh)
    segments, operations, captions = _compile_timeline_segments(plan, mesh_bbox)
    total_time_sec = segments[-1]["end_time_sec"] if segments else 0.0

    tri_model = None
    engine = None
    simulation_notes: list[dict] = []
    try:
        from src.simulation.material_removal import MaterialRemovalEngine
        from src.simulation.tri_dexel import TriDexelModel
    except ImportError:
        try:
            from simulation.material_removal import MaterialRemovalEngine
            from simulation.tri_dexel import TriDexelModel
        except ImportError as exc:
            MaterialRemovalEngine = None
            TriDexelModel = None
            simulation_notes.append({
                "severity": "warning",
                "message": f"Tri-dexel simulation unavailable: {exc}",
            })

    if TriDexelModel is not None and MaterialRemovalEngine is not None:
        try:
            tri_model = TriDexelModel.from_mesh(
                initial_mesh,
                resolution=max(float(resolution_mm), 0.01),
            )
            engine = MaterialRemovalEngine(
                tri_dexel=tri_model,
                linear_resolution=max(float(resolution_mm), 0.01),
            )
        except Exception as exc:
            tri_model = None
            engine = None
            simulation_notes.append({
                "severity": "warning",
                "message": f"Tri-dexel initialization failed: {exc}",
            })

    keyframes: list[dict] = []
    keyframe_times = _keyframe_times(total_time_sec, keyframe_interval_sec, max_keyframes)
    keyframe_cursor = 0

    def capture_keyframe(
        *,
        time_sec: float,
        sequence_number: Any,
        operation: str,
        label: str,
        force: bool = False,
    ) -> None:
        nonlocal keyframe_cursor

        if not force:
            while (
                keyframe_cursor < len(keyframe_times)
                and keyframe_times[keyframe_cursor] < time_sec - 1e-9
            ):
                keyframe_cursor += 1
            if (
                keyframe_cursor >= len(keyframe_times)
                or abs(keyframe_times[keyframe_cursor] - time_sec) > 1e-6
            ):
                return
            keyframe_cursor += 1

        if keyframes and abs(float(keyframes[-1]["time_sec"]) - float(time_sec)) < 1e-6:
            keyframes[-1].update({
                "sequence_number": sequence_number,
                "operation": operation,
                "label": label,
            })
            return

        mesh_path = None
        mesh_format = None
        volume = None
        if tri_model is not None:
            volume = _round_float(tri_model.volume())
        if states_dir is not None:
            filename = f"stock_t{len(keyframes):04d}_{_time_slug(time_sec)}.stl"
            path = states_dir / filename
            exported = _export_simulation_mesh(
                tri_model,
                path,
                fallback_mesh=initial_mesh,
            )
            if exported:
                mesh_path = f"simulation_states/{filename}"
                mesh_format = "stl"

        keyframes.append({
            "index": len(keyframes),
            "time_sec": _round_float(time_sec),
            "sequence_number": sequence_number,
            "operation": operation,
            "label": label,
            "path": mesh_path,
            "format": mesh_format,
            "role": "simulation_stock_state",
            "volume_mm3": volume,
        })

    capture_keyframe(
        time_sec=0.0,
        sequence_number=0,
        operation="initial_stock",
        label="Initial stock",
        force=True,
    )

    if engine is not None:
        _replay_segments(
            segments,
            engine=engine,
            mesh_bbox=mesh_bbox,
            keyframe_times=keyframe_times,
            capture_keyframe=capture_keyframe,
            notes=simulation_notes,
        )

    final_op = operations[-1] if operations else {}
    capture_keyframe(
        time_sec=total_time_sec,
        sequence_number=final_op.get("sequence_number", plan.get("total_operations", 0)),
        operation=final_op.get("operation", "final_stock"),
        label="Final simulated stock",
        force=True,
    )

    fidelity = {
        "stock_geometry": "tri_dexel_material_removal" if engine is not None else "metadata_only",
        "cad_boundary": "simulation keyframes are mesh snapshots; final STEP remains CadQuery/B-Rep output",
        "processes": _process_fidelity(plan.get("operations", [])),
        "notes": simulation_notes,
    }

    return {
        "schema_version": SIMULATION_TIMELINE_SCHEMA_VERSION,
        "units": "mm",
        "source_plan": {
            "schema_version": plan.get("schema_version"),
            "operation_count": len(plan.get("operations", [])),
            "material": plan.get("material"),
            "stock_dimensions": plan.get("stock_dimensions", {}),
        },
        "timeline": {
            "fps": int(fps),
            "playback_rate": float(playback_rate),
            "total_time_sec": _round_float(total_time_sec),
            "keyframe_interval_sec": float(keyframe_interval_sec),
            "segments": segments,
        },
        "operations": operations,
        "tools": _tool_payloads(plan.get("operations", [])),
        "machines": _machine_payloads(plan, include_machine=include_machine),
        "fixtures": plan.get("fixture") if include_fixtures else None,
        "stock_keyframes": keyframes,
        "captions": captions,
        "fidelity": fidelity,
        "performance": {
            "generation_time_sec": _round_float(time.perf_counter() - started),
            "resolution_mm": float(resolution_mm),
            "keyframe_count": len(keyframes),
            "initial_stock_source": initial_source,
        },
    }


def export_simulation_package(
    stock: Any,
    output_dir: str | Path,
    *,
    target: Any = None,
    tolerance_mm: float = 0.25,
    include_diff_mesh: bool = True,
    economics: Any = None,
    fps: int = 30,
    playback_rate: float = 1.0,
    resolution_mm: float = 0.5,
    keyframe_interval_sec: float = 0.25,
    include_machine: bool = True,
    include_fixtures: bool = True,
    include_process_effects: bool = True,
    max_keyframes: int = 240,
) -> dict:
    """Export a browser visualization package with time-based simulation data."""

    from .visualization import export_visualization_package

    out = Path(output_dir)
    scene = export_visualization_package(
        stock,
        out,
        target=target,
        tolerance_mm=tolerance_mm,
        include_diff_mesh=include_diff_mesh,
        economics=economics,
        title="SubCAD Operation Simulation Session",
    )

    timeline = build_simulation_timeline(
        stock,
        output_dir=out,
        fps=fps,
        playback_rate=playback_rate,
        resolution_mm=resolution_mm,
        keyframe_interval_sec=keyframe_interval_sec,
        target=target,
        include_machine=include_machine,
        include_fixtures=include_fixtures,
        include_process_effects=include_process_effects,
        max_keyframes=max_keyframes,
    )

    timeline_path = out / "simulation_timeline.json"
    _write_json(timeline_path, timeline)

    assets = dict(scene.get("assets") or {})
    assets["simulation_timeline"] = {
        "path": "simulation_timeline.json",
        "format": "json",
        "schema_version": SIMULATION_TIMELINE_SCHEMA_VERSION,
        "total_time_sec": timeline["timeline"]["total_time_sec"],
        "keyframe_count": len(timeline.get("stock_keyframes", [])),
    }
    assets["simulation_states"] = {
        "path": "simulation_states/",
        "format": "stl",
        "state_count": len([
            state for state in timeline.get("stock_keyframes", [])
            if state.get("path")
        ]),
    }
    assets["video_manifest"] = {
        "path": "video_manifest.json",
        "format": "json",
        "schema_version": "subcad.video_manifest.v1",
        "preferred_format": "webm",
    }
    scene["assets"] = assets
    scene["simulation"] = {
        "schema_version": SIMULATION_TIMELINE_SCHEMA_VERSION,
        "timeline_path": "simulation_timeline.json",
        "total_time_sec": timeline["timeline"]["total_time_sec"],
        "keyframe_count": len(timeline.get("stock_keyframes", [])),
        "fidelity": timeline.get("fidelity", {}),
    }
    machines = timeline.get("machines") or []
    if machines:
        scene["machines"] = machines
        scene["machine"] = scene.get("machine") or machines[0]

    video_manifest = {
        "schema_version": "subcad.video_manifest.v1",
        "timeline": "simulation_timeline.json",
        "scene": "scene.json",
        "preferred_format": "webm",
        "fps": int(fps),
        "duration_sec": timeline["timeline"]["total_time_sec"],
        "playback_rate": float(playback_rate),
    }
    _write_json(out / "scene.json", scene)
    _write_json(out / "video_manifest.json", video_manifest)
    return scene


def _compile_timeline_segments(plan: dict, mesh_bbox: dict) -> tuple[list[dict], list[dict], list[dict]]:
    segments: list[dict] = []
    operations: list[dict] = []
    captions: list[dict] = []
    current_time = 0.0
    previous_tool_key = None
    previous_setup = None

    for op in plan.get("operations", []):
        setup = op.get("setup")
        if previous_setup is not None and setup and setup != previous_setup:
            duration = 5.0
            segment = _segment(
                "setup_transition",
                current_time,
                current_time + duration,
                op,
                label=f"Move to setup {setup}",
            )
            segments.append(segment)
            captions.append(_caption(segment, f"Setup change: {previous_setup} to {setup}"))
            current_time += duration

        tool_key = _tool_key(op)
        if previous_tool_key is not None and tool_key != previous_tool_key:
            duration = 3.0
            segment = _segment(
                "tool_change",
                current_time,
                current_time + duration,
                op,
                label=f"Tool change to {_tool_label(op)}",
            )
            segments.append(segment)
            captions.append(_caption(segment, f"Tool change: {_tool_label(op)}"))
            current_time += duration

        op_start = current_time
        moves = _operation_moves(op, mesh_bbox)
        move_segments, current_time = _compile_move_segments(op, moves, current_time)
        segments.extend(move_segments)
        op_end = current_time

        operations.append({
            "sequence_number": op.get("sequence_number"),
            "operation": op.get("operation"),
            "setup": setup,
            "machine": _operation_machine(op, plan),
            "tool": op.get("tool"),
            "tool_type": op.get("tool_type"),
            "tool_diameter_mm": op.get("tool_diameter_mm"),
            "start_time_sec": _round_float(op_start),
            "end_time_sec": _round_float(op_end),
            "duration_sec": _round_float(op_end - op_start),
            "fidelity": _operation_fidelity(op),
        })
        if op_end > op_start:
            captions.append({
                "start_time_sec": _round_float(op_start),
                "end_time_sec": _round_float(min(op_end, op_start + 2.0)),
                "sequence_number": op.get("sequence_number"),
                "text": f"OP {op.get('sequence_number')}: {op.get('operation')}",
            })

        previous_tool_key = tool_key
        previous_setup = setup or previous_setup

    return segments, operations, captions


def _compile_move_segments(op: dict, moves: list[dict], start_time: float) -> tuple[list[dict], float]:
    if len(moves) < 2:
        expected = max(_operation_time_sec(op), 0.25)
        segment = _segment(
            "process_move",
            start_time,
            start_time + expected,
            op,
            label=op.get("operation"),
        )
        return [segment], start_time + expected

    raw: list[dict] = []
    for index in range(1, len(moves)):
        previous = moves[index - 1]
        move = moves[index]
        move_type = _move_type(move)
        start = previous.get("position")
        end = move.get("position")
        if not start or not end:
            continue
        length = _distance(start, end)
        duration = _move_duration_sec(previous, move, length)
        segment_type = "cutting_move" if _is_cutting_move(move, end) else f"{move_type}_move"
        if move_type in _NON_CUTTING_MOVES:
            segment_type = "rapid_move" if move_type in {"rapid", "retract"} else "inspection_or_pause"
        raw.append({
            "move_index": index,
            "segment_type": segment_type,
            "move_type": move_type,
            "start_position": start,
            "end_position": end,
            "start_pose": previous.get("pose"),
            "end_pose": move.get("pose"),
            "duration_sec": duration,
            "cutting": segment_type == "cutting_move",
            "feed_mm_min": move.get("feed_mm_min"),
            "dwell_seconds": move.get("dwell_seconds"),
        })

    if not raw:
        return [], start_time

    expected = _operation_time_sec(op)
    raw_total = sum(item["duration_sec"] for item in raw)
    scale = expected / raw_total if expected > 0.0 and raw_total > 0.0 else 1.0

    current = start_time
    compiled = []
    for item in raw:
        duration = max(item["duration_sec"] * scale, 0.01)
        segment = _segment(
            item["segment_type"],
            current,
            current + duration,
            op,
            label=op.get("operation"),
        )
        segment.update({
            "move_index": item["move_index"],
            "move_type": item["move_type"],
            "start_position": item["start_position"],
            "end_position": item["end_position"],
            "start_pose": item["start_pose"],
            "end_pose": item["end_pose"],
            "cutting": item["cutting"],
            "feed_mm_min": item["feed_mm_min"],
            "dwell_seconds": item["dwell_seconds"],
        })
        compiled.append(segment)
        current += duration
    return compiled, current


def _replay_segments(
    segments: list[dict],
    *,
    engine: Any,
    mesh_bbox: dict,
    keyframe_times: list[float],
    capture_keyframe,
    notes: list[dict],
) -> None:
    tools: dict[str, Any] = {}

    for segment in segments:
        if not segment.get("cutting"):
            continue

        start_pose_data = segment.get("start_pose")
        end_pose_data = segment.get("end_pose")
        if not start_pose_data or not end_pose_data:
            continue

        tool = _simulation_tool(segment, tools, notes)
        if tool is None:
            continue

        frame_times = [
            t for t in keyframe_times
            if segment["start_time_sec"] < t <= segment["end_time_sec"] + 1e-9
        ]
        if segment["end_time_sec"] not in frame_times:
            frame_times.append(segment["end_time_sec"])
        frame_times = sorted(set(round(t, 9) for t in frame_times))

        previous_time = segment["start_time_sec"]
        previous_pose = _pose_from_payload(start_pose_data)
        if previous_pose is None:
            continue

        for frame_time in frame_times:
            if segment["end_time_sec"] <= segment["start_time_sec"]:
                local = 1.0
            else:
                local = (
                    (frame_time - segment["start_time_sec"])
                    / (segment["end_time_sec"] - segment["start_time_sec"])
                )
            pose_payload = _interpolate_pose_payload(start_pose_data, end_pose_data, local)
            next_pose = _pose_from_payload(pose_payload)
            if next_pose is None:
                continue
            try:
                engine.remove_tool_swept(tool, previous_pose, next_pose)
            except Exception:
                try:
                    engine.remove_tool_at_pose(tool, next_pose)
                except Exception as exc:
                    notes.append({
                        "severity": "warning",
                        "sequence_number": segment.get("sequence_number"),
                        "message": f"Material removal failed: {exc}",
                    })
                    break

            previous_time = frame_time
            previous_pose = next_pose
            capture_keyframe(
                time_sec=frame_time,
                sequence_number=segment.get("sequence_number"),
                operation=segment.get("operation"),
                label=f"OP {segment.get('sequence_number')} at {_round_float(frame_time)} s",
            )


def _simulation_tool(segment: dict, cache: dict[str, Any], notes: list[dict]):
    try:
        from src.simulation.tools import create_tool as sim_create_tool
    except ImportError:
        try:
            from simulation.tools import create_tool as sim_create_tool
        except ImportError as exc:
            notes.append({"severity": "warning", "message": f"Tool simulation unavailable: {exc}"})
            return None

    tool_type = str(segment.get("tool_type") or "flat_endmill")
    sim_tool_key = _TOOL_TYPE_MAP.get(tool_type)
    if sim_tool_key is None:
        notes.append({
            "severity": "warning",
            "sequence_number": segment.get("sequence_number"),
            "message": f"Skipped operation-video removal for unsupported tool_type={tool_type!r}",
        })
        return None
    diameter = float(segment.get("tool_diameter_mm") or 10.0)
    cache_key = f"{sim_tool_key}:{diameter:g}"
    if cache_key not in cache:
        try:
            cache[cache_key] = sim_create_tool(sim_tool_key, diameter=diameter)
        except Exception as exc:
            notes.append({
                "severity": "warning",
                "sequence_number": segment.get("sequence_number"),
                "message": f"Tool creation failed for operation-video replay: {exc}",
            })
            return None
    return cache[cache_key]


def _operation_moves(op: dict, mesh_bbox: dict) -> list[dict]:
    data = op.get("toolpath")
    records: list[Any] = []
    if isinstance(data, dict):
        if isinstance(data.get("moves"), list):
            records = data["moves"]
        elif isinstance(data.get("positions"), list):
            records = data["positions"]
        elif data.get("position") is not None:
            records = [data]
    elif isinstance(data, list):
        records = data

    if not records:
        try:
            from .stock import _op_to_simple_toolpath

            records = _op_to_simple_toolpath(op, mesh_bbox)
        except Exception:
            records = []

    moves = []
    top_z = float(mesh_bbox.get("z_max", 0.0))
    for record in records:
        normalized = _normalize_move(record, top_z)
        if normalized is not None:
            moves.append(normalized)
    return moves


def _normalize_move(record: Any, top_z: float) -> dict | None:
    if hasattr(record, "position"):
        position = [float(v) for v in record.position[:3]]
        orientation = [float(v) for v in getattr(record, "orientation", [1.0, 0.0, 0.0, 0.0])[:4]]
        move_type = "feed"
        feed = None
        dwell = 0.0
        mesh_position = position
        program_position = [position[0], position[1], position[2] - top_z]
    elif isinstance(record, dict):
        raw_position = record.get("position")
        if raw_position is None and all(key in record for key in ("x", "y", "z")):
            raw_position = [record["x"], record["y"], record["z"]]
        if raw_position is None or len(raw_position) < 3:
            return None
        position = [float(v) for v in raw_position[:3]]
        orientation = [float(v) for v in record.get("orientation", [1.0, 0.0, 0.0, 0.0])[:4]]
        move_type = _move_type(record)
        feed = _as_float(record.get("feed_mm_min", record.get("feed")))
        dwell = _as_float(record.get("dwell_seconds")) or 0.0
        mesh_position = [position[0], position[1], position[2] + top_z]
        program_position = position
    elif isinstance(record, (list, tuple)) and len(record) >= 3:
        position = [float(v) for v in record[:3]]
        orientation = [1.0, 0.0, 0.0, 0.0]
        move_type = "feed"
        feed = None
        dwell = 0.0
        mesh_position = [position[0], position[1], position[2] + top_z]
        program_position = position
    else:
        return None

    return {
        "type": move_type,
        "position": [_round_float(v) for v in mesh_position],
        "program_position": [_round_float(v) for v in program_position],
        "pose": {
            "position": [_round_float(v) for v in mesh_position],
            "orientation": [_round_float(v) for v in orientation],
        },
        "feed_mm_min": feed,
        "dwell_seconds": dwell,
    }


def _pose_from_payload(payload: dict):
    try:
        from src.simulation.kinematics import ToolPose
    except ImportError:
        from simulation.kinematics import ToolPose
    import numpy as np

    position = payload.get("position")
    orientation = payload.get("orientation", [1.0, 0.0, 0.0, 0.0])
    if not position:
        return None
    return ToolPose(
        position=np.array(position, dtype=np.float64),
        orientation=np.array(orientation, dtype=np.float64),
    )


def _interpolate_pose_payload(start: dict, end: dict, t: float) -> dict:
    t = max(0.0, min(1.0, float(t)))
    start_pos = start.get("position", [0.0, 0.0, 0.0])
    end_pos = end.get("position", start_pos)
    return {
        "position": [
            float(start_pos[i]) + (float(end_pos[i]) - float(start_pos[i])) * t
            for i in range(3)
        ],
        "orientation": end.get("orientation") or start.get("orientation") or [1.0, 0.0, 0.0, 0.0],
    }


def _initial_stock_mesh(stock: Any) -> tuple[Any, str]:
    from .geometry import (
        create_cylindrical_stock,
        create_rectangular_stock,
        to_mesh,
    )

    history = list(getattr(stock, "_state_history", []) or [])
    if history:
        shape = history[0].get("shape")
        if shape is not None:
            try:
                mesh = to_mesh(shape)
                if mesh is not None:
                    return mesh, "_state_history[0]"
            except Exception:
                pass

    dims = dict(getattr(stock, "_stock_dims", {}) or {})
    try:
        if all(key in dims for key in ("length", "width", "height")):
            mesh = to_mesh(create_rectangular_stock(
                float(dims["length"]),
                float(dims["width"]),
                float(dims["height"]),
            ))
            if mesh is not None:
                return mesh, "stock_dimensions.rectangular"
        if all(key in dims for key in ("diameter", "height")):
            mesh = to_mesh(create_cylindrical_stock(
                float(dims["diameter"]),
                float(dims["height"]),
            ))
            if mesh is not None:
                return mesh, "stock_dimensions.cylindrical"
    except Exception:
        pass

    try:
        mesh = stock.to_mesh()
        if mesh is not None:
            return mesh, "current_shape_fallback"
    except Exception:
        pass
    return None, "unavailable"


def _export_simulation_mesh(tri_model: Any, path: Path, *, fallback_mesh: Any = None) -> bool:
    mesh = None
    if tri_model is not None:
        try:
            from src.simulation.surface import tri_dexel_to_mesh
        except ImportError:
            try:
                from simulation.surface import tri_dexel_to_mesh
            except ImportError:
                tri_dexel_to_mesh = None
        if tri_dexel_to_mesh is not None:
            try:
                mesh = tri_dexel_to_mesh(tri_model)
            except Exception:
                mesh = None
    vertices = getattr(mesh, "vertices", []) if mesh is not None else []
    if mesh is None or len(vertices) == 0:
        mesh = fallback_mesh
    if mesh is None:
        return False
    try:
        mesh.export(str(path))
        return path.exists() and path.stat().st_size > 0
    except Exception:
        return False


def _keyframe_times(total_time_sec: float, interval_sec: float, max_keyframes: int) -> list[float]:
    total = max(float(total_time_sec or 0.0), 0.0)
    if total <= 0.0:
        return [0.0]
    interval = max(float(interval_sec or 0.0), 0.001)
    max_keyframes = max(int(max_keyframes or 1), 2)
    if math.floor(total / interval) + 1 > max_keyframes:
        interval = total / float(max_keyframes - 1)
    times = [0.0]
    current = interval
    while current < total - 1e-9:
        times.append(current)
        current += interval
    times.append(total)
    return times


def _segment(segment_type: str, start: float, end: float, op: dict, *, label: str | None = None) -> dict:
    return {
        "id": f"{segment_type}_{len(str(start))}_{op.get('sequence_number', 'x')}",
        "segment_type": segment_type,
        "start_time_sec": _round_float(start),
        "end_time_sec": _round_float(end),
        "duration_sec": _round_float(end - start),
        "sequence_number": op.get("sequence_number"),
        "operation": op.get("operation"),
        "setup": op.get("setup"),
        "machine": op.get("machine"),
        "tool_id": ((op.get("tool") or {}).get("catalog_id") or ""),
        "tool_type": op.get("tool_type"),
        "tool_diameter_mm": op.get("tool_diameter_mm"),
        "cutting": False,
        "label": label or op.get("operation") or segment_type,
        "fidelity": _operation_fidelity(op),
    }


def _caption(segment: dict, text: str) -> dict:
    return {
        "start_time_sec": segment["start_time_sec"],
        "end_time_sec": segment["end_time_sec"],
        "sequence_number": segment.get("sequence_number"),
        "text": text,
    }


def _operation_time_sec(op: dict) -> float:
    summary = op.get("toolpath_summary") or {}
    pass_plan = op.get("pass_plan") or {}
    economics = op.get("economics") or {}
    value = (
        summary.get("estimated_time_min")
        or summary.get("estimated_time_minutes")
        or pass_plan.get("estimated_time_min")
        or pass_plan.get("estimated_time_minutes")
        or economics.get("estimated_time_minutes")
    )
    minutes = _as_float(value)
    if minutes is not None and minutes > 0.0:
        return minutes * 60.0

    toolpath = op.get("toolpath") if isinstance(op.get("toolpath"), dict) else {}
    value = toolpath.get("estimated_time_min") or toolpath.get("estimated_time_minutes")
    minutes = _as_float(value)
    if minutes is not None and minutes > 0.0:
        return minutes * 60.0
    return 1.0


def _move_duration_sec(previous: dict, move: dict, length_mm: float) -> float:
    move_type = _move_type(move)
    if move_type == "dwell":
        return max(float(move.get("dwell_seconds") or 0.25), 0.01)
    if move_type in {"rapid", "retract"}:
        return max(length_mm / 5000.0 * 60.0, 0.05)
    feed = _as_float(move.get("feed_mm_min")) or _as_float(previous.get("feed_mm_min")) or 1000.0
    return max(length_mm / max(feed, 1e-9) * 60.0, 0.05)


def _is_cutting_move(move: dict, end_position: list[float]) -> bool:
    move_type = _move_type(move)
    if move_type not in _CUTTING_MOVES:
        return False
    program = move.get("program_position") or []
    if len(program) >= 3:
        return float(program[2]) <= 0.0
    return bool(end_position)


def _move_type(move: Any) -> str:
    if isinstance(move, dict):
        raw = str(move.get("type") or move.get("move_type") or move.get("kind") or "feed").lower()
    else:
        raw = "feed"
    if "rapid" in raw:
        return "rapid"
    if "plunge" in raw:
        return "plunge"
    if "retract" in raw:
        return "retract"
    if "dwell" in raw:
        return "dwell"
    if "arc" in raw:
        return "arc"
    return "feed"


def _tool_payloads(operations: list[dict]) -> list[dict]:
    tools = {}
    for op in operations:
        key = _tool_key(op)
        if not key:
            continue
        tools[key] = {
            "id": key,
            "label": _tool_label(op),
            "tool": op.get("tool"),
            "tool_type": op.get("tool_type"),
            "diameter_mm": op.get("tool_diameter_mm"),
        }
    return list(tools.values())


def _machine_payloads(plan: dict, *, include_machine: bool) -> list[dict]:
    if not include_machine:
        return []
    machine = plan.get("machine")
    if isinstance(machine, dict) and machine:
        return [machine]
    if _plan_uses_turning(plan):
        try:
            from .machine_context import load_machine_context

            return [load_machine_context("generic_lathe").to_dict()]
        except Exception:
            return [_inline_generic_lathe_machine()]
    return [{"id": "generic_machine", "name": "Generic machine", "fidelity": "placeholder"}]


def _plan_uses_turning(plan: dict) -> bool:
    operations = plan.get("operations", []) if isinstance(plan, dict) else []
    for op in operations:
        text = " ".join(
            str(op.get(key) or "")
            for key in ("operation", "process", "tool_type", "strategy")
            if isinstance(op, dict)
        ).lower()
        if "turn" in text or "lathe" in text or "boring" in text:
            return True
    return False


def _inline_generic_lathe_machine() -> dict:
    return {
        "machine_id": "generic_lathe",
        "name": "Generic 2-Axis CNC Lathe",
        "manufacturer": "Generic",
        "model": "2-Axis Turning Center",
        "axes": ["X", "Z"],
        "linear_limits": {"X": [0.0, 120.0], "Z": [-150.0, 150.0]},
        "rotary_limits": {},
        "axis_limits": {
            "X": {"limits": [0.0, 120.0], "max_feed": 10000, "rapid_feed": 18000, "type": "linear_axis"},
            "Z": {"limits": [-150.0, 150.0], "max_feed": 12000, "rapid_feed": 24000, "type": "linear_axis"},
        },
        "spindle": {"max_rpm": 4500, "max_power_kw": 15, "max_torque_nm": 180, "label": "Main Spindle"},
        "capabilities": {
            "schema_version": "subcad.machine_capabilities.v1",
            "processes": ["turn"],
            "operation_families": [
                "turn_profile",
                "turn_face",
                "turn_od",
                "turn_id",
                "turn_groove",
                "turn_thread",
                "mill_turn_setup",
            ],
            "controller_cycles": ["G71", "G72", "G76", "G96", "G97"],
            "coolant": ["flood"],
            "probing": False,
            "tool_interface": "VDI40",
            "tool_capacity": 12,
        },
        "components": [
            {"id": "bed", "type": "static", "parent": None, "label": "Lathe Bed", "mesh": None,
             "transform": [0, 0, 0, 0, 0, 0], "visual": {"shape": "box", "size_mm": [190, 34, 16]}},
            {"id": "headstock", "type": "static", "parent": "bed", "label": "Headstock Casting", "mesh": None,
             "transform": [-78, 0, 24, 0, 0, 0], "visual": {"shape": "box", "size_mm": [32, 92, 76]}},
            {"id": "spindle", "type": "spindle", "parent": "headstock", "label": "Main Spindle", "mesh": None,
             "transform": [-58, 0, 24, 0, 0, 0], "axis": "Z", "max_rpm": 4500},
            {"id": "chuck", "type": "workholding", "parent": "spindle", "label": "Hydraulic 3-Jaw Chuck",
             "fixture_type": "lathe_chuck", "mesh": None, "transform": [-52, 0, 24, 0, 0, 0],
             "grip_diameter_range_mm": [10, 90],
             "visual": {"shape": "cylinder", "axis": "X", "diameter_mm": 86, "length_mm": 18,
                        "jaw_count": 3, "jaw_length_mm": 18, "jaw_width_mm": 9}},
            {"id": "tailstock", "type": "tailstock", "parent": "bed", "label": "Tailstock With Live Center",
             "mesh": None, "transform": [74, 0, 19, 0, 0, 0],
             "visual": {"body_size_mm": [26, 50, 42], "center_length_mm": 24, "center_diameter_mm": 16}},
            {"id": "tool_mount", "type": "tool_mount", "parent": "bed", "label": "Turret Tool Station",
             "mesh": None, "transform": [10, 68, 38, 0, 0, 0],
             "visual": {"shape": "box", "size_mm": [26, 26, 22]}},
        ],
    }


def _process_fidelity(operations: list[dict]) -> list[dict]:
    return [
        {
            "sequence_number": op.get("sequence_number"),
            "operation": op.get("operation"),
            "fidelity": _operation_fidelity(op),
        }
        for op in operations
    ]


def _operation_fidelity(op: dict) -> str:
    operation = str(op.get("operation") or "").lower()
    tool_type = str(op.get("tool_type") or "").lower()
    if "turn" in operation:
        return "timeline_only_turning_v1_pending"
    if "laser" in operation or tool_type == "fiber_laser":
        return "visual_process_approximation"
    if "press_brake" in operation or "bend" in operation:
        return "visual_deformation_approximation"
    if "wire" in operation or "edm" in operation:
        return "visual_process_approximation"
    return "tri_dexel_material_removal"


def _operation_machine(op: dict, plan: dict) -> Any:
    if op.get("machine"):
        return op.get("machine")
    machine = plan.get("machine")
    if isinstance(machine, dict):
        return machine.get("id") or machine.get("machine_id") or machine.get("name")
    return None


def _tool_key(op: dict) -> str:
    tool = op.get("tool") or {}
    assembly = tool.get("assembly") or {}
    return str(
        assembly.get("tool_id")
        or tool.get("catalog_id")
        or op.get("tool_type")
        or ""
    )


def _tool_label(op: dict) -> str:
    tool = op.get("tool") or {}
    assembly = tool.get("assembly") or {}
    tool_id = assembly.get("tool_id") or tool.get("catalog_id") or op.get("tool_type") or "tool"
    dia = op.get("tool_diameter_mm") or tool.get("diameter_mm")
    return f"{tool_id} ({dia:g} mm)" if isinstance(dia, (int, float)) else str(tool_id)


def _mesh_bbox(mesh: Any) -> dict:
    bounds = getattr(mesh, "bounds", None)
    if bounds is None:
        return {
            "x_min": 0.0, "x_max": 0.0,
            "y_min": 0.0, "y_max": 0.0,
            "z_min": 0.0, "z_max": 0.0,
        }
    bmin = bounds[0]
    bmax = bounds[1]
    return {
        "x_min": float(bmin[0]),
        "x_max": float(bmax[0]),
        "y_min": float(bmin[1]),
        "y_max": float(bmax[1]),
        "z_min": float(bmin[2]),
        "z_max": float(bmax[2]),
        "length": float(bmax[0] - bmin[0]),
        "width": float(bmax[1] - bmin[1]),
        "height": float(bmax[2] - bmin[2]),
    }


def _distance(a: list[float], b: list[float]) -> float:
    return math.dist([float(v) for v in a[:3]], [float(v) for v in b[:3]])


def _as_float(value: Any) -> float | None:
    try:
        if value is None:
            return None
        result = float(value)
        if math.isfinite(result):
            return result
    except (TypeError, ValueError):
        return None
    return None


def _round_float(value: Any, digits: int = 6) -> float | None:
    numeric = _as_float(value)
    if numeric is None:
        return None
    return round(numeric, digits)


def _time_slug(time_sec: float) -> str:
    return f"{max(float(time_sec), 0.0):010.3f}".replace(".", "_")


def _write_json(path: Path, data: Any) -> None:
    with path.open("w", encoding="utf-8") as fh:
        json.dump(_json_ready(data), fh, indent=2)


def _json_ready(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(k): _json_ready(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_ready(v) for v in value]
    if hasattr(value, "tolist"):
        return value.tolist()
    return value


def _error_timeline(
    plan: dict,
    *,
    error: str,
    fps: int,
    playback_rate: float,
    resolution_mm: float,
) -> dict:
    return {
        "schema_version": SIMULATION_TIMELINE_SCHEMA_VERSION,
        "units": "mm",
        "source_plan": {
            "schema_version": plan.get("schema_version"),
            "operation_count": len(plan.get("operations", [])),
            "material": plan.get("material"),
            "stock_dimensions": plan.get("stock_dimensions", {}),
        },
        "timeline": {
            "fps": int(fps),
            "playback_rate": float(playback_rate),
            "total_time_sec": 0.0,
            "keyframe_interval_sec": 0.0,
            "segments": [],
        },
        "operations": [],
        "tools": [],
        "machines": [],
        "fixtures": None,
        "stock_keyframes": [],
        "captions": [],
        "fidelity": {
            "stock_geometry": "unavailable",
            "cad_boundary": "simulation keyframes are mesh snapshots; final STEP remains CadQuery/B-Rep output",
            "notes": [{"severity": "error", "message": error}],
        },
        "performance": {
            "generation_time_sec": 0.0,
            "resolution_mm": float(resolution_mm),
            "keyframe_count": 0,
            "initial_stock_source": "unavailable",
        },
    }
